/* ==========================================================
 * Проект: MOYAMOVA
 * Файл: trainer.prepositions.de.js
 * Назначение: Данные для тренера предлогов (DE) — 80 паттернов × 5 фраз (=400 упражнений)
 * Версия: 1.0
 * Обновлено: 2026-01-27
 * ========================================================== */

(function(){
  'use strict';

  var root = (window.prepositionsTrainer = window.prepositionsTrainer || {});
  root.de = {
    lang: 'de',
    totalPatterns: 80,
    variantsPerPattern: 5,

    // Пул предлогов-отвлекалок (уникальные подписи на кнопках — обязательны)
    distractorPool: [
      'in','auf','an','unter','über','zwischen','vor','hinter','neben',
      'zu','nach','von','bei','mit','aus','seit','gegenüber',
      'für','ohne','durch','gegen','um','bis'
    ],

    patterns: [
      { id: "de_prep_direction_001_in", answer: "in", items: ["Ich gehe ___ die Stadt.", "Wir fahren ___ die Schule.", "Er läuft ___ den Park.", "Sie geht ___ das Büro.", "Kommst du ___ das Kino?"], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_002_auf", answer: "auf", items: ["Er legt das Buch ___ die Stadt.", "Sie stellt die Tasse ___ die Schule.", "Wir setzen uns ___ die Stadt.", "Ich lege die Jacke ___ den Park.", "Stell die Tasche ___ das Kino."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_003_an", answer: "an", items: ["Ich hänge das Bild ___ den Park.", "Er stellt den Stuhl ___ den Park.", "Sie klebt das Poster ___ den Park.", "Wir lehnen das Fahrrad ___ das Kino.", "Leg das Handy ___ die Stadt."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_004_unter", answer: "unter", items: ["Er schiebt die Kiste ___ die Stadt.", "Ich lege die Schuhe ___ die Schule.", "Sie stellt die Tasche ___ den Park.", "Wir setzen uns ___ das Büro.", "Leg den Ball ___ das Kino."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_005_\u00fcber", answer: "\u00fcber", items: ["Wir gehen ___ den Park.", "Er hängt die Lampe ___ die Stadt.", "Sie springt ___ das Büro.", "Ich werfe den Mantel ___ die Schule.", "Geh ___ das Kino."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_006_zwischen", answer: "zwischen", items: ["Stell den Tisch ___ die Stadt.", "Ich lege das Buch ___ die Schule.", "Wir stellen die Pflanzen ___ den Park.", "Park das Auto ___ das Büro.", "Setz dich ___ das Kino."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_007_vor", answer: "vor", items: ["Stell dich ___ das Büro.", "Er parkt das Auto ___ das Kino.", "Wir legen die Matratze ___ die Stadt.", "Sie stellt die Schuhe ___ die Schule.", "Leg den Koffer ___ den Park."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_008_hinter", answer: "hinter", items: ["Stell das Fahrrad ___ das Kino.", "Ich lege das Paket ___ das Büro.", "Er stellt den Stuhl ___ die Stadt.", "Wir stellen die Kiste ___ die Schule.", "Park das Auto ___ den Park."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_009_neben", answer: "neben", items: ["Stell den Stuhl ___ das Kino.", "Ich lege das Buch ___ die Stadt.", "Er stellt die Tasche ___ die Schule.", "Wir setzen uns ___ den Park.", "Leg das Handy ___ das Büro."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_010_in", answer: "in", items: ["Ich gehe ___ den Tisch.", "Wir fahren ___ den Stuhl.", "Er läuft ___ die Wand.", "Sie geht ___ das Regal.", "Kommst du ___ den Schrank?"], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_011_auf", answer: "auf", items: ["Er legt das Buch ___ den Tisch.", "Sie stellt die Tasse ___ den Stuhl.", "Wir setzen uns ___ den Tisch.", "Ich lege die Jacke ___ die Wand.", "Stell die Tasche ___ den Schrank."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_012_an", answer: "an", items: ["Ich hänge das Bild ___ die Wand.", "Er stellt den Stuhl ___ die Wand.", "Sie klebt das Poster ___ die Wand.", "Wir lehnen das Fahrrad ___ den Schrank.", "Leg das Handy ___ den Tisch."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_013_unter", answer: "unter", items: ["Er schiebt die Kiste ___ den Tisch.", "Ich lege die Schuhe ___ den Stuhl.", "Sie stellt die Tasche ___ die Wand.", "Wir setzen uns ___ das Regal.", "Leg den Ball ___ den Schrank."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_014_\u00fcber", answer: "\u00fcber", items: ["Wir gehen ___ die Wand.", "Er hängt die Lampe ___ den Tisch.", "Sie springt ___ das Regal.", "Ich werfe den Mantel ___ den Stuhl.", "Geh ___ den Schrank."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_015_zwischen", answer: "zwischen", items: ["Stell den Tisch ___ den Tisch.", "Ich lege das Buch ___ den Stuhl.", "Wir stellen die Pflanzen ___ die Wand.", "Park das Auto ___ das Regal.", "Setz dich ___ den Schrank."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_016_vor", answer: "vor", items: ["Stell dich ___ das Regal.", "Er parkt das Auto ___ den Schrank.", "Wir legen die Matratze ___ den Tisch.", "Sie stellt die Schuhe ___ den Stuhl.", "Leg den Koffer ___ die Wand."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_017_hinter", answer: "hinter", items: ["Stell das Fahrrad ___ den Schrank.", "Ich lege das Paket ___ das Regal.", "Er stellt den Stuhl ___ den Tisch.", "Wir stellen die Kiste ___ den Stuhl.", "Park das Auto ___ die Wand."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_018_neben", answer: "neben", items: ["Stell den Stuhl ___ den Schrank.", "Ich lege das Buch ___ den Tisch.", "Er stellt die Tasche ___ den Stuhl.", "Wir setzen uns ___ die Wand.", "Leg das Handy ___ das Regal."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_019_in", answer: "in", items: ["Ich gehe ___ das Bett.", "Wir fahren ___ den Teppich.", "Er läuft ___ die Brücke.", "Sie geht ___ das Haus.", "Kommst du ___ das Auto?"], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_020_auf", answer: "auf", items: ["Er legt das Buch ___ das Bett.", "Sie stellt die Tasse ___ den Teppich.", "Wir setzen uns ___ das Bett.", "Ich lege die Jacke ___ die Brücke.", "Stell die Tasche ___ das Auto."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_location_021_in", answer: "in", items: ["Ich bin ___ der Stadt.", "Wir sind ___ der Schule.", "Das Café ist ___ dem Kino.", "Er wartet ___ dem Büro.", "Sie wohnt ___ der Stadt."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_022_auf", answer: "auf", items: ["Das Buch liegt ___ der Stadt.", "Die Tasse steht ___ der Schule.", "Wir sind ___ der Stadt.", "Die Jacke liegt ___ dem Park.", "Die Tasche liegt ___ dem Kino."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_023_an", answer: "an", items: ["Das Bild hängt ___ dem Park.", "Der Stuhl steht ___ dem Park.", "Das Poster hängt ___ dem Park.", "Das Fahrrad steht ___ dem Kino.", "Die Notiz hängt ___ der Stadt."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_024_unter", answer: "unter", items: ["Die Kiste steht ___ der Stadt.", "Die Schuhe liegen ___ der Schule.", "Die Tasche liegt ___ dem Park.", "Wir sitzen ___ dem Büro.", "Der Ball liegt ___ dem Kino."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_025_\u00fcber", answer: "\u00fcber", items: ["Die Lampe hängt ___ der Stadt.", "Das Regal ist ___ der Schule.", "Wir wohnen ___ dem Park.", "Die Decke hängt ___ dem Büro.", "Das Bild hängt ___ dem Kino."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_026_zwischen", answer: "zwischen", items: ["Der Tisch steht ___ der Stadt.", "Das Buch liegt ___ der Schule.", "Die Pflanzen stehen ___ dem Park.", "Das Auto steht ___ dem Büro.", "Er sitzt ___ dem Kino."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_027_vor", answer: "vor", items: ["Ich stehe ___ dem Büro.", "Das Auto steht ___ dem Kino.", "Wir treffen uns ___ der Stadt.", "Die Schuhe stehen ___ der Schule.", "Der Koffer liegt ___ dem Park."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_028_hinter", answer: "hinter", items: ["Das Fahrrad steht ___ dem Kino.", "Das Paket liegt ___ dem Büro.", "Der Stuhl steht ___ der Stadt.", "Die Kiste steht ___ der Schule.", "Das Auto steht ___ dem Park."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_029_neben", answer: "neben", items: ["Der Stuhl steht ___ dem Kino.", "Das Buch liegt ___ der Stadt.", "Die Tasche liegt ___ der Schule.", "Wir sitzen ___ dem Park.", "Das Handy liegt ___ dem Büro."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_030_in", answer: "in", items: ["Ich bin ___ dem Tisch.", "Wir sind ___ dem Stuhl.", "Das Café ist ___ dem Schrank.", "Er wartet ___ dem Regal.", "Sie wohnt ___ dem Tisch."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_031_auf", answer: "auf", items: ["Das Buch liegt ___ dem Tisch.", "Die Tasse steht ___ dem Stuhl.", "Wir sind ___ dem Tisch.", "Die Jacke liegt ___ der Wand.", "Die Tasche liegt ___ dem Schrank."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_032_an", answer: "an", items: ["Das Bild hängt ___ der Wand.", "Der Stuhl steht ___ der Wand.", "Das Poster hängt ___ der Wand.", "Das Fahrrad steht ___ dem Schrank.", "Die Notiz hängt ___ dem Tisch."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_033_unter", answer: "unter", items: ["Die Kiste steht ___ dem Tisch.", "Die Schuhe liegen ___ dem Stuhl.", "Die Tasche liegt ___ der Wand.", "Wir sitzen ___ dem Regal.", "Der Ball liegt ___ dem Schrank."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_034_\u00fcber", answer: "\u00fcber", items: ["Die Lampe hängt ___ dem Tisch.", "Das Regal ist ___ dem Stuhl.", "Wir wohnen ___ der Wand.", "Die Decke hängt ___ dem Regal.", "Das Bild hängt ___ dem Schrank."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_035_zwischen", answer: "zwischen", items: ["Der Tisch steht ___ dem Tisch.", "Das Buch liegt ___ dem Stuhl.", "Die Pflanzen stehen ___ der Wand.", "Das Auto steht ___ dem Regal.", "Er sitzt ___ dem Schrank."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_036_vor", answer: "vor", items: ["Ich stehe ___ dem Regal.", "Das Auto steht ___ dem Schrank.", "Wir treffen uns ___ dem Tisch.", "Die Schuhe stehen ___ dem Stuhl.", "Der Koffer liegt ___ der Wand."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_037_hinter", answer: "hinter", items: ["Das Fahrrad steht ___ dem Schrank.", "Das Paket liegt ___ dem Regal.", "Der Stuhl steht ___ dem Tisch.", "Die Kiste steht ___ dem Stuhl.", "Das Auto steht ___ der Wand."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_038_neben", answer: "neben", items: ["Der Stuhl steht ___ dem Schrank.", "Das Buch liegt ___ dem Tisch.", "Die Tasche liegt ___ dem Stuhl.", "Wir sitzen ___ der Wand.", "Das Handy liegt ___ dem Regal."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_039_in", answer: "in", items: ["Ich bin ___ dem Bett.", "Wir sind ___ dem Teppich.", "Das Café ist ___ dem Auto.", "Er wartet ___ dem Haus.", "Sie wohnt ___ dem Bett."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_040_auf", answer: "auf", items: ["Das Buch liegt ___ dem Bett.", "Die Tasse steht ___ dem Teppich.", "Wir sind ___ dem Bett.", "Die Jacke liegt ___ der Brücke.", "Die Tasche liegt ___ dem Auto."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_dative_041_zu", answer: "zu", items: ["Ich gehe ___ dem Arzt.", "Wir fahren ___ der Arbeit.", "Er kommt ___ der Party.", "Sie läuft ___ dem Bahnhof.", "Gehst du ___ deiner Freundin?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_042_nach", answer: "nach", items: ["Wir fahren ___ Berlin.", "Er fliegt ___ Deutschland.", "Sie geht ___ Hause.", "Ich ziehe ___ Zürich.", "Kommst du ___ Hamburg?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_043_von", answer: "von", items: ["Ich komme ___ der Schule.", "Er ist ___ dem Büro.", "Sie spricht ___ dem Lehrer.", "Wir sind ___ der Reise zurück.", "Das Geschenk ist ___ meiner Mutter."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_044_bei", answer: "bei", items: ["Ich bin ___ meiner Oma.", "Er wohnt ___ seinen Eltern.", "Wir treffen uns ___ dir.", "Sie arbeitet ___ einer Firma.", "Ich bleibe ___ meinem Freund."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_045_mit", answer: "mit", items: ["Ich fahre ___ dem Bus.", "Er kommt ___ dem Auto.", "Wir essen ___ Freunden.", "Sie schreibt ___ einem Stift.", "Ich spreche ___ dir."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_046_aus", answer: "aus", items: ["Ich komme ___ der Schweiz.", "Er nimmt das Buch ___ dem Regal.", "Sie holt Wasser ___ der Flasche.", "Wir gehen ___ dem Haus.", "Der Mann ist ___ der Stadt."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_047_seit", answer: "seit", items: ["Ich wohne ___ 2020 hier.", "Er arbeitet ___ einem Jahr hier.", "Wir kennen uns ___ der Schule.", "Sie wartet ___ Stunden.", "Das gilt ___ gestern."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_048_gegen\u00fcber", answer: "gegen\u00fcber", items: ["Die Bank ist ___ dem Park.", "Das Café liegt ___ der Schule.", "Er sitzt ___ mir.", "Die Apotheke ist ___ dem Bahnhof.", "Unser Haus steht ___ der Kirche."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_049_zu", answer: "zu", items: ["Ich gehe ___ dem Arzt.", "Wir fahren ___ der Arbeit.", "Er kommt ___ der Party.", "Sie läuft ___ dem Bahnhof.", "Gehst du ___ deiner Freundin?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_050_nach", answer: "nach", items: ["Wir fahren ___ Berlin.", "Er fliegt ___ Deutschland.", "Sie geht ___ Hause.", "Ich ziehe ___ Zürich.", "Kommst du ___ Hamburg?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_051_von", answer: "von", items: ["Ich komme ___ der Schule.", "Er ist ___ dem Büro.", "Sie spricht ___ dem Lehrer.", "Wir sind ___ der Reise zurück.", "Das Geschenk ist ___ meiner Mutter."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_052_bei", answer: "bei", items: ["Ich bin ___ meiner Oma.", "Er wohnt ___ seinen Eltern.", "Wir treffen uns ___ dir.", "Sie arbeitet ___ einer Firma.", "Ich bleibe ___ meinem Freund."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_053_mit", answer: "mit", items: ["Ich fahre ___ dem Bus.", "Er kommt ___ dem Auto.", "Wir essen ___ Freunden.", "Sie schreibt ___ einem Stift.", "Ich spreche ___ dir."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_054_aus", answer: "aus", items: ["Ich komme ___ der Schweiz.", "Er nimmt das Buch ___ dem Regal.", "Sie holt Wasser ___ der Flasche.", "Wir gehen ___ dem Haus.", "Der Mann ist ___ der Stadt."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_055_seit", answer: "seit", items: ["Ich wohne ___ 2020 hier.", "Er arbeitet ___ einem Jahr hier.", "Wir kennen uns ___ der Schule.", "Sie wartet ___ Stunden.", "Das gilt ___ gestern."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_056_gegen\u00fcber", answer: "gegen\u00fcber", items: ["Die Bank ist ___ dem Park.", "Das Café liegt ___ der Schule.", "Er sitzt ___ mir.", "Die Apotheke ist ___ dem Bahnhof.", "Unser Haus steht ___ der Kirche."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_057_zu", answer: "zu", items: ["Ich gehe ___ dem Arzt.", "Wir fahren ___ der Arbeit.", "Er kommt ___ der Party.", "Sie läuft ___ dem Bahnhof.", "Gehst du ___ deiner Freundin?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_058_nach", answer: "nach", items: ["Wir fahren ___ Berlin.", "Er fliegt ___ Deutschland.", "Sie geht ___ Hause.", "Ich ziehe ___ Zürich.", "Kommst du ___ Hamburg?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_059_von", answer: "von", items: ["Ich komme ___ der Schule.", "Er ist ___ dem Büro.", "Sie spricht ___ dem Lehrer.", "Wir sind ___ der Reise zurück.", "Das Geschenk ist ___ meiner Mutter."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_060_bei", answer: "bei", items: ["Ich bin ___ meiner Oma.", "Er wohnt ___ seinen Eltern.", "Wir treffen uns ___ dir.", "Sie arbeitet ___ einer Firma.", "Ich bleibe ___ meinem Freund."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_accusative_061_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_062_ohne", answer: "ohne", items: ["Ich gehe ___ dich.", "Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Sie kommt ___ ihre Schwester.", "Das geht nicht ___ Probleme."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_063_durch", answer: "durch", items: ["Wir gehen ___ den Park.", "Er läuft ___ die Stadt.", "Sie schaut ___ das Fenster.", "Ich gehe ___ die Tür.", "Wir fahren ___ den Tunnel."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_064_gegen", answer: "gegen", items: ["Ich bin ___ diese Idee.", "Er kämpft ___ den Wind.", "Wir spielen ___ ein anderes Team.", "Sie ist ___ meinen Plan.", "Das hilft ___ Kopfschmerzen."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_065_um", answer: "um", items: ["Wir gehen ___ den See.", "Er läuft ___ das Haus.", "Sie steht ___ 7 Uhr auf.", "Ich bitte ___ Hilfe.", "Es geht ___ das Geld."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_066_bis", answer: "bis", items: ["Wir bleiben ___ morgen.", "Er arbeitet ___ 18 Uhr.", "Ich warte ___ nächste Woche.", "Sie läuft ___ die Ecke.", "Bleib ___ Ende hier."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_067_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_068_ohne", answer: "ohne", items: ["Ich gehe ___ dich.", "Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Sie kommt ___ ihre Schwester.", "Das geht nicht ___ Probleme."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_069_durch", answer: "durch", items: ["Wir gehen ___ den Park.", "Er läuft ___ die Stadt.", "Sie schaut ___ das Fenster.", "Ich gehe ___ die Tür.", "Wir fahren ___ den Tunnel."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_070_gegen", answer: "gegen", items: ["Ich bin ___ diese Idee.", "Er kämpft ___ den Wind.", "Wir spielen ___ ein anderes Team.", "Sie ist ___ meinen Plan.", "Das hilft ___ Kopfschmerzen."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_071_um", answer: "um", items: ["Wir gehen ___ den See.", "Er läuft ___ das Haus.", "Sie steht ___ 7 Uhr auf.", "Ich bitte ___ Hilfe.", "Es geht ___ das Geld."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_072_bis", answer: "bis", items: ["Wir bleiben ___ morgen.", "Er arbeitet ___ 18 Uhr.", "Ich warte ___ nächste Woche.", "Sie läuft ___ die Ecke.", "Bleib ___ Ende hier."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_073_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_074_ohne", answer: "ohne", items: ["Ich gehe ___ dich.", "Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Sie kommt ___ ihre Schwester.", "Das geht nicht ___ Probleme."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_075_durch", answer: "durch", items: ["Wir gehen ___ den Park.", "Er läuft ___ die Stadt.", "Sie schaut ___ das Fenster.", "Ich gehe ___ die Tür.", "Wir fahren ___ den Tunnel."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_076_gegen", answer: "gegen", items: ["Ich bin ___ diese Idee.", "Er kämpft ___ den Wind.", "Wir spielen ___ ein anderes Team.", "Sie ist ___ meinen Plan.", "Das hilft ___ Kopfschmerzen."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_077_um", answer: "um", items: ["Wir gehen ___ den See.", "Er läuft ___ das Haus.", "Sie steht ___ 7 Uhr auf.", "Ich bitte ___ Hilfe.", "Es geht ___ das Geld."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_078_bis", answer: "bis", items: ["Wir bleiben ___ morgen.", "Er arbeitet ___ 18 Uhr.", "Ich warte ___ nächste Woche.", "Sie läuft ___ die Ecke.", "Bleib ___ Ende hier."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_079_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_080_ohne", answer: "ohne", items: ["Ich gehe ___ dich.", "Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Sie kommt ___ ihre Schwester.", "Das geht nicht ___ Probleme."], meta:{ bucket:"accusative", case:"Akk" } },
    ]
  };
})();
