/* ==========================================================
 * Проект: MOYAMOVA
 * Файл: trainer.prepositions.de.js
 * Назначение: Данные для тренера предлогов (DE) — 80 паттернов × 5 фраз (=400 упражнений)
 * Версия: 1.0
 * Обновлено: 2026-01-27
 * ========================================================== */

(function(){
  'use strict';

  var root = (window.prepositionsTrainer = window.prepositionsTrainer || {});
  root.de = {
    lang: 'de',
    totalPatterns: 80,
    variantsPerPattern: 5,

    // Пул предлогов-отвлекалок (уникальные подписи на кнопках — обязательны)
    distractorPool: [
      'in','auf','an','unter','über','zwischen','vor','hinter','neben',
      'zu','nach','von','bei','mit','aus','seit','gegenüber',
      'für','ohne','durch','gegen','um','bis'
    ],

    patterns: [
      { id: "de_prep_direction_001_in", answer: "in", items: ["Ich gehe ___ die Stadt.", "Wir fahren ___ die Schule.", "Er geht ___ das Büro.", "Sie kommt ___ das Kino.", "Komm bitte ___ die Küche."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_002_auf", answer: "auf", items: ["Er legt das Buch ___ den Tisch.", "Sie stellt die Tasse ___ den Stuhl.", "Leg das Handy ___ den Schreibtisch.", "Stell die Tasche ___ den Boden.", "Wir setzen uns ___ das Sofa."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_003_an", answer: "an", items: ["Ich hänge das Bild ___ die Wand.", "Kleb das Poster ___ die Tür.", "Stell den Stuhl ___ den Tisch.", "Lehn das Fahrrad ___ den Zaun.", "Leg den Spiegel ___ das Fenster."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_004_unter", answer: "unter", items: ["Er schiebt die Kiste ___ den Tisch.", "Ich lege die Schuhe ___ das Bett.", "Stell die Tasche ___ den Stuhl.", "Leg den Ball ___ die Bank.", "Wir setzen uns ___ den Baum."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_005_\u00fcber", answer: "\u00fcber", items: ["Wir gehen ___ die Straße.", "Er springt ___ den Zaun.", "Sie läuft ___ die Brücke.", "Wir fahren ___ den Fluss.", "Geh ___ den Hügel!"], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_006_zwischen", answer: "zwischen", items: ["Stell den Tisch ___ die Stühle.", "Leg das Buch ___ die Hefte.", "Stell die Pflanzen ___ die Fenster.", "Park das Auto ___ die Autos.", "Setz dich ___ die Kinder."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_007_vor", answer: "vor", items: ["Stell dich ___ das Haus.", "Stell das Fahrrad ___ die Tür.", "Leg die Matte ___ den Eingang.", "Setz dich ___ den Fernseher.", "Leg den Koffer ___ die Treppe."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_008_hinter", answer: "hinter", items: ["Stell das Auto ___ das Haus.", "Leg das Paket ___ die Tür.", "Stell den Stuhl ___ den Schrank.", "Geh ___ den Bahnhof.", "Setz dich ___ die Hecke."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_009_neben", answer: "neben", items: ["Stell den Stuhl ___ den Tisch.", "Leg das Buch ___ das Bett.", "Stell die Tasche ___ die Tür.", "Park das Auto ___ das Haus.", "Leg das Handy ___ den Laptop."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_010_in", answer: "in", items: ["Ich gehe ___ die Stadt.", "Wir fahren ___ die Schule.", "Er geht ___ das Büro.", "Sie kommt ___ das Kino.", "Komm bitte ___ die Küche."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_011_auf", answer: "auf", items: ["Er legt das Buch ___ den Tisch.", "Sie stellt die Tasse ___ den Stuhl.", "Leg das Handy ___ den Schreibtisch.", "Stell die Tasche ___ den Boden.", "Wir setzen uns ___ das Sofa."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_012_an", answer: "an", items: ["Ich hänge das Bild ___ die Wand.", "Kleb das Poster ___ die Tür.", "Stell den Stuhl ___ den Tisch.", "Lehn das Fahrrad ___ den Zaun.", "Leg den Spiegel ___ das Fenster."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_013_unter", answer: "unter", items: ["Er schiebt die Kiste ___ den Tisch.", "Ich lege die Schuhe ___ das Bett.", "Stell die Tasche ___ den Stuhl.", "Leg den Ball ___ die Bank.", "Wir setzen uns ___ den Baum."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_014_\u00fcber", answer: "\u00fcber", items: ["Wir gehen ___ die Straße.", "Er springt ___ den Zaun.", "Sie läuft ___ die Brücke.", "Wir fahren ___ den Fluss.", "Geh ___ den Hügel!"], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_015_zwischen", answer: "zwischen", items: ["Stell den Tisch ___ die Stühle.", "Leg das Buch ___ die Hefte.", "Stell die Pflanzen ___ die Fenster.", "Park das Auto ___ die Autos.", "Setz dich ___ die Kinder."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_016_vor", answer: "vor", items: ["Stell dich ___ das Haus.", "Stell das Fahrrad ___ die Tür.", "Leg die Matte ___ den Eingang.", "Setz dich ___ den Fernseher.", "Leg den Koffer ___ die Treppe."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_017_hinter", answer: "hinter", items: ["Stell das Auto ___ das Haus.", "Leg das Paket ___ die Tür.", "Stell den Stuhl ___ den Schrank.", "Geh ___ den Bahnhof.", "Setz dich ___ die Hecke."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_018_neben", answer: "neben", items: ["Stell den Stuhl ___ den Tisch.", "Leg das Buch ___ das Bett.", "Stell die Tasche ___ die Tür.", "Park das Auto ___ das Haus.", "Leg das Handy ___ den Laptop."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_019_in", answer: "in", items: ["Ich gehe ___ die Stadt.", "Wir fahren ___ die Schule.", "Er geht ___ das Büro.", "Sie kommt ___ das Kino.", "Komm bitte ___ die Küche."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_020_auf", answer: "auf", items: ["Er legt das Buch ___ den Tisch.", "Sie stellt die Tasse ___ den Stuhl.", "Leg das Handy ___ den Schreibtisch.", "Stell die Tasche ___ den Boden.", "Wir setzen uns ___ das Sofa."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_location_021_in", answer: "in", items: ["Ich bin ___ der Stadt.", "Wir sind ___ der Schule.", "Er ist ___ dem Büro.", "Sie ist ___ der Küche.", "Das Café ist ___ dem Kino."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_022_auf", answer: "auf", items: ["Das Buch liegt ___ dem Tisch.", "Die Tasse steht ___ dem Stuhl.", "Die Tasche liegt ___ dem Boden.", "Wir sitzen ___ dem Sofa.", "Er steht ___ dem Balkon."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_023_an", answer: "an", items: ["Das Bild hängt ___ der Wand.", "Das Poster hängt ___ der Tür.", "Der Kalender hängt ___ der Wand.", "Er steht ___ der Tür.", "Die Gardine hängt ___ dem Fenster."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_024_unter", answer: "unter", items: ["Die Kiste steht ___ dem Tisch.", "Die Schuhe liegen ___ dem Bett.", "Der Hund schläft ___ dem Tisch.", "Die Tasche liegt ___ dem Regal.", "Der Schlüssel liegt ___ der Matte."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_025_\u00fcber", answer: "\u00fcber", items: ["Die Lampe hängt ___ dem Tisch.", "Die Brücke ist ___ dem Fluss.", "Der Himmel ist ___ der Stadt.", "Die Wohnung liegt ___ der Bäckerei.", "Das Bild hängt ___ dem Bett."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_026_zwischen", answer: "zwischen", items: ["Der Tisch steht ___ den Stühlen.", "Das Café liegt ___ den Häusern.", "Wir stehen ___ den Bäumen.", "Das Auto steht ___ den Autos.", "Er sitzt ___ den Kindern."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_027_vor", answer: "vor", items: ["Ich stehe ___ dem Haus.", "Wir warten ___ dem Eingang.", "Das Fahrrad steht ___ der Tür.", "Der Koffer liegt ___ der Treppe.", "Sie sitzt ___ dem Fernseher."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_028_hinter", answer: "hinter", items: ["Das Auto steht ___ dem Haus.", "Die Hecke ist ___ dem Garten.", "Der Stuhl steht ___ dem Schrank.", "Wir treffen uns ___ dem Bahnhof.", "Das Paket liegt ___ der Tür."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_029_neben", answer: "neben", items: ["Der Stuhl steht ___ dem Tisch.", "Das Buch liegt ___ dem Bett.", "Die Tasche steht ___ der Tür.", "Das Handy liegt ___ dem Laptop.", "Das Auto steht ___ dem Haus."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_030_in", answer: "in", items: ["Ich bin ___ der Stadt.", "Wir sind ___ der Schule.", "Er ist ___ dem Büro.", "Sie ist ___ der Küche.", "Das Café ist ___ dem Kino."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_031_auf", answer: "auf", items: ["Das Buch liegt ___ dem Tisch.", "Die Tasse steht ___ dem Stuhl.", "Die Tasche liegt ___ dem Boden.", "Wir sitzen ___ dem Sofa.", "Er steht ___ dem Balkon."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_032_an", answer: "an", items: ["Das Bild hängt ___ der Wand.", "Das Poster hängt ___ der Tür.", "Der Kalender hängt ___ der Wand.", "Er steht ___ der Tür.", "Die Gardine hängt ___ dem Fenster."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_033_unter", answer: "unter", items: ["Die Kiste steht ___ dem Tisch.", "Die Schuhe liegen ___ dem Bett.", "Der Hund schläft ___ dem Tisch.", "Die Tasche liegt ___ dem Regal.", "Der Schlüssel liegt ___ der Matte."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_034_\u00fcber", answer: "\u00fcber", items: ["Die Lampe hängt ___ dem Tisch.", "Die Brücke ist ___ dem Fluss.", "Der Himmel ist ___ der Stadt.", "Die Wohnung liegt ___ der Bäckerei.", "Das Bild hängt ___ dem Bett."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_035_zwischen", answer: "zwischen", items: ["Der Tisch steht ___ den Stühlen.", "Das Café liegt ___ den Häusern.", "Wir stehen ___ den Bäumen.", "Das Auto steht ___ den Autos.", "Er sitzt ___ den Kindern."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_036_vor", answer: "vor", items: ["Ich stehe ___ dem Haus.", "Wir warten ___ dem Eingang.", "Das Fahrrad steht ___ der Tür.", "Der Koffer liegt ___ der Treppe.", "Sie sitzt ___ dem Fernseher."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_037_hinter", answer: "hinter", items: ["Das Auto steht ___ dem Haus.", "Die Hecke ist ___ dem Garten.", "Der Stuhl steht ___ dem Schrank.", "Wir treffen uns ___ dem Bahnhof.", "Das Paket liegt ___ der Tür."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_038_neben", answer: "neben", items: ["Der Stuhl steht ___ dem Tisch.", "Das Buch liegt ___ dem Bett.", "Die Tasche steht ___ der Tür.", "Das Handy liegt ___ dem Laptop.", "Das Auto steht ___ dem Haus."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_039_in", answer: "in", items: ["Ich bin ___ der Stadt.", "Wir sind ___ der Schule.", "Er ist ___ dem Büro.", "Sie ist ___ der Küche.", "Das Café ist ___ dem Kino."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_040_auf", answer: "auf", items: ["Das Buch liegt ___ dem Tisch.", "Die Tasse steht ___ dem Stuhl.", "Die Tasche liegt ___ dem Boden.", "Wir sitzen ___ dem Sofa.", "Er steht ___ dem Balkon."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_dative_041_zu", answer: "zu", items: ["Ich gehe ___ dem Arzt.", "Wir fahren ___ der Arbeit.", "Er kommt ___ der Party.", "Sie läuft ___ dem Bahnhof.", "Kommst du ___ mir?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_042_nach", answer: "nach", items: ["Wir fahren ___ Berlin.", "Er fliegt ___ Deutschland.", "Sie geht ___ Hause.", "Ich ziehe ___ Zürich.", "Kommst du ___ Hamburg?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_043_von", answer: "von", items: ["Ich komme ___ der Schule.", "Er kommt ___ dem Bahnhof.", "Sie ist ___ der Arbeit.", "Das Geschenk ist ___ meiner Mutter.", "Die Nachricht ist ___ meinem Bruder."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_044_bei", answer: "bei", items: ["Ich bin ___ meiner Oma.", "Er wohnt ___ seinen Eltern.", "Wir treffen uns ___ dir.", "Sie arbeitet ___ einer Firma.", "Ich bleibe ___ meinem Freund."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_045_mit", answer: "mit", items: ["Ich fahre ___ dem Bus.", "Sie fährt ___ dem Fahrrad.", "Wir essen ___ Freunden.", "Er telefoniert ___ seiner Schwester.", "Ich spreche ___ dir."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_046_aus", answer: "aus", items: ["Ich komme ___ der Schweiz.", "Er nimmt das Buch ___ dem Regal.", "Sie holt Wasser ___ der Flasche.", "Ich nehme den Schlüssel ___ der Tasche.", "Wir gehen ___ dem Haus."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_047_seit", answer: "seit", items: ["Ich wohne ___ 2020 hier.", "Er arbeitet ___ einem Jahr hier.", "Wir kennen uns ___ der Schule.", "Ich lerne Deutsch ___ zwei Monaten.", "Sie wartet ___ Stunden."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_048_gegen\u00fcber", answer: "gegen\u00fcber", items: ["Die Bank ist ___ dem Park.", "Das Café liegt ___ der Schule.", "Er sitzt ___ mir.", "Die Apotheke ist ___ dem Bahnhof.", "Unser Haus steht ___ der Kirche."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_049_zu", answer: "zu", items: ["Ich gehe ___ dem Arzt.", "Wir fahren ___ der Arbeit.", "Er kommt ___ der Party.", "Sie läuft ___ dem Bahnhof.", "Kommst du ___ mir?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_050_nach", answer: "nach", items: ["Wir fahren ___ Berlin.", "Er fliegt ___ Deutschland.", "Sie geht ___ Hause.", "Ich ziehe ___ Zürich.", "Kommst du ___ Hamburg?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_051_von", answer: "von", items: ["Ich komme ___ der Schule.", "Er kommt ___ dem Bahnhof.", "Sie ist ___ der Arbeit.", "Das Geschenk ist ___ meiner Mutter.", "Die Nachricht ist ___ meinem Bruder."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_052_bei", answer: "bei", items: ["Ich bin ___ meiner Oma.", "Er wohnt ___ seinen Eltern.", "Wir treffen uns ___ dir.", "Sie arbeitet ___ einer Firma.", "Ich bleibe ___ meinem Freund."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_053_mit", answer: "mit", items: ["Ich fahre ___ dem Bus.", "Sie fährt ___ dem Fahrrad.", "Wir essen ___ Freunden.", "Er telefoniert ___ seiner Schwester.", "Ich spreche ___ dir."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_054_aus", answer: "aus", items: ["Ich komme ___ der Schweiz.", "Er nimmt das Buch ___ dem Regal.", "Sie holt Wasser ___ der Flasche.", "Ich nehme den Schlüssel ___ der Tasche.", "Wir gehen ___ dem Haus."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_055_seit", answer: "seit", items: ["Ich wohne ___ 2020 hier.", "Er arbeitet ___ einem Jahr hier.", "Wir kennen uns ___ der Schule.", "Ich lerne Deutsch ___ zwei Monaten.", "Sie wartet ___ Stunden."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_056_gegen\u00fcber", answer: "gegen\u00fcber", items: ["Die Bank ist ___ dem Park.", "Das Café liegt ___ der Schule.", "Er sitzt ___ mir.", "Die Apotheke ist ___ dem Bahnhof.", "Unser Haus steht ___ der Kirche."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_057_zu", answer: "zu", items: ["Ich gehe ___ dem Arzt.", "Wir fahren ___ der Arbeit.", "Er kommt ___ der Party.", "Sie läuft ___ dem Bahnhof.", "Kommst du ___ mir?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_058_nach", answer: "nach", items: ["Wir fahren ___ Berlin.", "Er fliegt ___ Deutschland.", "Sie geht ___ Hause.", "Ich ziehe ___ Zürich.", "Kommst du ___ Hamburg?"], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_059_von", answer: "von", items: ["Ich komme ___ der Schule.", "Er kommt ___ dem Bahnhof.", "Sie ist ___ der Arbeit.", "Das Geschenk ist ___ meiner Mutter.", "Die Nachricht ist ___ meinem Bruder."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_060_bei", answer: "bei", items: ["Ich bin ___ meiner Oma.", "Er wohnt ___ seinen Eltern.", "Wir treffen uns ___ dir.", "Sie arbeitet ___ einer Firma.", "Ich bleibe ___ meinem Freund."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_accusative_061_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_062_ohne", answer: "ohne", items: ["Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Ich kann nicht ___ dich.", "Sie arbeitet ___ Pause.", "Das klappt nicht ___ Plan."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_063_durch", answer: "durch", items: ["Wir gehen ___ den Park.", "Sie schaut ___ das Fenster.", "Ich gehe ___ die Tür.", "Wir fahren ___ den Tunnel.", "Der Zug fährt ___ die Schweiz."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_064_gegen", answer: "gegen", items: ["Wir sind ___ Gewalt.", "Sie protestiert ___ die Entscheidung.", "Das Medikament wirkt ___ Schmerzen.", "Der Ball prallt ___ die Wand.", "Er kämpft ___ den Wind."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_065_um", answer: "um", items: ["Wir gehen ___ den See.", "Er läuft ___ das Haus.", "Ich bitte ___ Hilfe.", "Es geht ___ das Geld.", "Wir treffen uns ___ 18 Uhr."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_066_bis", answer: "bis", items: ["Wir bleiben ___ morgen.", "Er arbeitet ___ 18 Uhr.", "Ich warte ___ nächste Woche.", "Die Ausstellung geht ___ Sonntag.", "Bleib ___ Ende hier."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_067_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_068_ohne", answer: "ohne", items: ["Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Ich kann nicht ___ dich.", "Sie arbeitet ___ Pause.", "Das klappt nicht ___ Plan."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_069_durch", answer: "durch", items: ["Wir gehen ___ den Park.", "Sie schaut ___ das Fenster.", "Ich gehe ___ die Tür.", "Wir fahren ___ den Tunnel.", "Der Zug fährt ___ die Schweiz."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_070_gegen", answer: "gegen", items: ["Wir sind ___ Gewalt.", "Sie protestiert ___ die Entscheidung.", "Das Medikament wirkt ___ Schmerzen.", "Der Ball prallt ___ die Wand.", "Er kämpft ___ den Wind."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_071_um", answer: "um", items: ["Wir gehen ___ den See.", "Er läuft ___ das Haus.", "Ich bitte ___ Hilfe.", "Es geht ___ das Geld.", "Wir treffen uns ___ 18 Uhr."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_072_bis", answer: "bis", items: ["Wir bleiben ___ morgen.", "Er arbeitet ___ 18 Uhr.", "Ich warte ___ nächste Woche.", "Die Ausstellung geht ___ Sonntag.", "Bleib ___ Ende hier."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_073_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_074_ohne", answer: "ohne", items: ["Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Ich kann nicht ___ dich.", "Sie arbeitet ___ Pause.", "Das klappt nicht ___ Plan."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_075_durch", answer: "durch", items: ["Wir gehen ___ den Park.", "Sie schaut ___ das Fenster.", "Ich gehe ___ die Tür.", "Wir fahren ___ den Tunnel.", "Der Zug fährt ___ die Schweiz."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_076_gegen", answer: "gegen", items: ["Wir sind ___ Gewalt.", "Sie protestiert ___ die Entscheidung.", "Das Medikament wirkt ___ Schmerzen.", "Der Ball prallt ___ die Wand.", "Er kämpft ___ den Wind."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_077_um", answer: "um", items: ["Wir gehen ___ den See.", "Er läuft ___ das Haus.", "Ich bitte ___ Hilfe.", "Es geht ___ das Geld.", "Wir treffen uns ___ 18 Uhr."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_078_bis", answer: "bis", items: ["Wir bleiben ___ morgen.", "Er arbeitet ___ 18 Uhr.", "Ich warte ___ nächste Woche.", "Die Ausstellung geht ___ Sonntag.", "Bleib ___ Ende hier."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_079_f\u00fcr", answer: "f\u00fcr", items: ["Das ist ___ dich.", "Ich kaufe Blumen ___ meine Mutter.", "Wir sparen ___ den Urlaub.", "Er arbeitet ___ eine Firma.", "Danke ___ deine Hilfe."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_080_ohne", answer: "ohne", items: ["Wir trinken Kaffee ___ Milch.", "Er fährt ___ Führerschein.", "Ich kann nicht ___ dich.", "Sie arbeitet ___ Pause.", "Das klappt nicht ___ Plan."], meta:{ bucket:"accusative", case:"Akk" } },
    ]
  };
})();
