/* ==========================================================
 * Проект: MOYAMOVA
 * Файл: trainer.prepositions.de.js
 * Назначение: Данные для тренера предлогов (DE) — 80 паттернов × 5 фраз (=400 упражнений)
 * Версия: 1.0
 * Обновлено: 2026-01-27
 * ========================================================== */

(function(){
  'use strict';

  var root = (window.prepositionsTrainer = window.prepositionsTrainer || {});
  root.de = {
    lang: 'de',
    totalPatterns: 80,
    variantsPerPattern: 5,

    // Пул предлогов-отвлекалок (уникальные подписи на кнопках — обязательны)
    distractorPool: [
      'in','auf','an','unter','über','zwischen','vor','hinter','neben',
      'zu','nach','von','bei','mit','aus','seit','gegenüber',
      'für','ohne','durch','gegen','um','bis'
    ],

    patterns: [
      { id: "de_prep_direction_001_in", answer: "in", items: ["Wir gehen ___ den Supermarkt.", "Er fährt ___ die Stadt.", "Komm bitte ___ das Büro.", "Sie läuft ___ das Zimmer.", "Ich steige ___ den Bus."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_002_auf", answer: "auf", items: ["Häng das Bild ___ die Wand.", "Kletter ___ den Baum.", "Setz dich ___ den Stuhl.", "Leg das Buch ___ den Tisch.", "Stell die Flasche ___ den Boden."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_003_an", answer: "an", items: ["Schreib deinen Namen ___ die Tafel.", "Stell das Fahrrad ___ die Wand.", "Häng die Jacke ___ den Haken.", "Setz dich ___ den Tisch.", "Komm ___ das Fenster."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_004_unter", answer: "unter", items: ["Setz dich ___ den Baum.", "Schieb den Stuhl ___ den Tisch.", "Stell die Tasche ___ den Stuhl.", "Stell die Kiste ___ das Bett.", "Leg den Ball ___ den Tisch."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_005_\u00fcber", answer: "\u00fcber", items: ["Ich gehe ___ das Haus.", "Wir treffen uns ___ dem Park.", "Ich bin ___ dem Haus.", "Das Buch liegt ___ dem Tisch.", "Leg das Buch ___ den Tisch heute."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_006_zwischen", answer: "zwischen", items: ["Leg das Buch ___ den Laptop und die Tasse.", "Stell die Tasche ___ den Schrank und die Tür.", "Stell den Stuhl ___ den Tisch und das Bett.", "Park das Auto ___ den Bus und das Taxi.", "Setz dich ___ mich und Anna."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_007_vor", answer: "vor", items: ["Stell den Stuhl ___ den Tisch.", "Stell die Schuhe ___ die Tür.", "Setz dich ___ den Fernseher.", "Park das Auto ___ das Haus.", "Leg den Rucksack ___ die Bank."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_008_hinter", answer: "hinter", items: ["Setz dich ___ den Vorhang.", "Leg den Ball ___ das Sofa.", "Stell den Koffer ___ die Tür.", "Park das Auto ___ den Bus.", "Geh ___ das Haus."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_009_neben", answer: "neben", items: ["Park das Fahrrad ___ die Tür.", "Setz dich ___ mich.", "Leg den Schlüssel ___ das Handy.", "Stell die Lampe ___ das Bett.", "Stell den Stuhl ___ den Tisch heute."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_010_in", answer: "in", items: ["Die Kinder rennen ___ die Schule.", "Ich gehe ___ die Küche.", "Sie läuft ___ das Zimmer heute.", "Er fährt ___ die Stadt jetzt.", "Komm bitte ___ das Büro am Morgen."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_011_auf", answer: "auf", items: ["Kletter ___ den Baum heute.", "Kletter ___ den Baum jetzt.", "Häng das Bild ___ die Wand am Morgen.", "Leg das Buch ___ den Tisch bitte.", "Kletter ___ den Baum gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_012_an", answer: "an", items: ["Schreib deinen Namen ___ die Tafel heute.", "Komm ___ das Fenster jetzt.", "Häng die Jacke ___ den Haken am Morgen.", "Komm ___ das Fenster bitte.", "Komm ___ das Fenster gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_013_unter", answer: "unter", items: ["Schieb den Stuhl ___ den Tisch heute.", "Setz dich ___ den Baum jetzt.", "Schieb den Stuhl ___ den Tisch am Morgen.", "Setz dich ___ den Baum bitte.", "Setz dich ___ den Baum gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_014_\u00fcber", answer: "\u00fcber", items: ["Ich bin ___ dem Haus heute.", "Wir treffen uns ___ dem Park jetzt.", "Ich gehe ___ das Haus am Morgen.", "Wir treffen uns ___ dem Park bitte.", "Ich bin ___ dem Haus gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_015_zwischen", answer: "zwischen", items: ["Park das Auto ___ den Bus und das Taxi heute.", "Leg das Buch ___ den Laptop und die Tasse jetzt.", "Setz dich ___ mich und Anna am Morgen.", "Stell den Stuhl ___ den Tisch und das Bett bitte.", "Stell den Stuhl ___ den Tisch und das Bett gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_016_vor", answer: "vor", items: ["Stell den Stuhl ___ den Tisch heute.", "Park das Auto ___ das Haus jetzt.", "Park das Auto ___ das Haus am Morgen.", "Leg den Rucksack ___ die Bank bitte.", "Park das Auto ___ das Haus gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_017_hinter", answer: "hinter", items: ["Setz dich ___ den Vorhang heute.", "Park das Auto ___ den Bus jetzt.", "Geh ___ das Haus am Morgen.", "Stell den Koffer ___ die Tür bitte.", "Stell den Koffer ___ die Tür gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_018_neben", answer: "neben", items: ["Setz dich ___ mich heute.", "Park das Fahrrad ___ die Tür jetzt.", "Stell die Lampe ___ das Bett am Morgen.", "Setz dich ___ mich bitte.", "Setz dich ___ mich gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_019_in", answer: "in", items: ["Ich gehe ___ die Küche heute.", "Ich gehe ___ die Küche jetzt.", "Ich steige ___ den Bus am Morgen.", "Ich gehe ___ die Küche bitte.", "Komm bitte ___ das Büro gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_direction_020_auf", answer: "auf", items: ["Stell die Flasche ___ den Boden heute.", "Häng das Bild ___ die Wand jetzt.", "Stell die Flasche ___ den Boden am Morgen.", "Setz dich ___ den Stuhl bitte.", "Kletter ___ den Baum gleich."], meta:{ bucket:"direction", case:"Akk" } },
      { id: "de_prep_location_021_in", answer: "in", items: ["Wir sitzen ___ der Küche.", "Der Hund schläft ___ dem Haus.", "Das Handy liegt ___ dem Bett.", "Ich bin ___ der Schule.", "Der Schlüssel ist ___ der Tasche."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_022_auf", answer: "auf", items: ["Der Teller steht ___ dem Tisch.", "Wir sind ___ dem Balkon.", "Die Katze sitzt ___ dem Sofa.", "Das Bild hängt ___ der Wand.", "Wir sind ___ dem Balkon heute."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_023_an", answer: "an", items: ["Das Fahrrad steht ___ der Wand.", "Wir sitzen ___ dem Tisch.", "Die Jacke hängt ___ dem Haken.", "Er steht ___ der Tür.", "Die Jacke hängt ___ dem Haken heute."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_024_unter", answer: "unter", items: ["Wir stehen ___ dem Baum.", "Die Katze schläft ___ dem Stuhl.", "Die Kiste steht ___ dem Bett.", "Der Schlüssel ist ___ dem Teppich.", "Der Ball liegt ___ dem Tisch."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_025_\u00fcber", answer: "\u00fcber", items: ["Das Buch liegt ___ dem Tisch heute.", "Ich gehe ___ das Haus jetzt.", "Das Buch liegt ___ dem Tisch am Morgen.", "Ich bin ___ dem Haus bitte.", "Wir treffen uns ___ dem Park gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_026_zwischen", answer: "zwischen", items: ["Die Tasche liegt ___ dem Schrank und der Tür.", "Der Stuhl steht ___ dem Tisch und dem Bett.", "Das Auto steht ___ dem Bus und dem Taxi.", "Er sitzt ___ mir und Anna.", "Das Buch liegt ___ dem Laptop und der Tasse."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_027_vor", answer: "vor", items: ["Er wartet ___ dem Kino.", "Wir treffen uns ___ der Schule.", "Die Schuhe stehen ___ der Tür.", "Der Hund sitzt ___ der Bank.", "Das Auto steht ___ dem Haus."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_028_hinter", answer: "hinter", items: ["Der Garten ist ___ dem Haus.", "Der Bus steht ___ dem Auto.", "Die Kinder spielen ___ dem Haus.", "Das Fahrrad steht ___ der Garage.", "Der Hund liegt ___ dem Sofa."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_029_neben", answer: "neben", items: ["Der Schlüssel liegt ___ dem Handy.", "Er sitzt ___ mir.", "Die Lampe steht ___ dem Bett.", "Das Fahrrad steht ___ der Tür.", "Der Stuhl steht ___ dem Tisch."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_030_in", answer: "in", items: ["Sie ist ___ dem Kino.", "Wir sitzen ___ der Küche heute.", "Ich bin ___ der Schule jetzt.", "Sie ist ___ dem Kino am Morgen.", "Sie ist ___ dem Kino bitte."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_031_auf", answer: "auf", items: ["Das Bild hängt ___ der Wand heute.", "Die Katze sitzt ___ dem Sofa jetzt.", "Der Teller steht ___ dem Tisch am Morgen.", "Das Buch liegt ___ dem Tisch bitte.", "Das Bild hängt ___ der Wand gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_032_an", answer: "an", items: ["Die Jacke hängt ___ dem Haken heute.", "Die Jacke hängt ___ dem Haken jetzt.", "Das Fahrrad steht ___ der Wand am Morgen.", "Das Bild hängt ___ der Wand bitte.", "Das Fahrrad steht ___ der Wand gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_033_unter", answer: "unter", items: ["Die Katze schläft ___ dem Stuhl heute.", "Wir stehen ___ dem Baum jetzt.", "Die Katze schläft ___ dem Stuhl am Morgen.", "Die Katze schläft ___ dem Stuhl bitte.", "Die Katze schläft ___ dem Stuhl gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_034_\u00fcber", answer: "\u00fcber", items: ["Leg das Buch ___ den Tisch heute.", "Wir treffen uns ___ dem Park jetzt.", "Ich bin ___ dem Haus am Morgen.", "Ich bin ___ dem Haus bitte.", "Ich bin ___ dem Haus gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_035_zwischen", answer: "zwischen", items: ["Der Stuhl steht ___ dem Tisch und dem Bett heute.", "Die Tasche liegt ___ dem Schrank und der Tür jetzt.", "Er sitzt ___ mir und Anna am Morgen.", "Der Stuhl steht ___ dem Tisch und dem Bett bitte.", "Das Auto steht ___ dem Bus und dem Taxi gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_036_vor", answer: "vor", items: ["Wir treffen uns ___ der Schule heute.", "Die Schuhe stehen ___ der Tür jetzt.", "Die Schuhe stehen ___ der Tür am Morgen.", "Er wartet ___ dem Kino bitte.", "Er wartet ___ dem Kino gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_037_hinter", answer: "hinter", items: ["Der Garten ist ___ dem Haus heute.", "Der Bus steht ___ dem Auto jetzt.", "Die Kinder spielen ___ dem Haus am Morgen.", "Der Bus steht ___ dem Auto bitte.", "Der Hund liegt ___ dem Sofa gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_038_neben", answer: "neben", items: ["Der Stuhl steht ___ dem Tisch heute.", "Der Stuhl steht ___ dem Tisch jetzt.", "Er sitzt ___ mir am Morgen.", "Der Stuhl steht ___ dem Tisch bitte.", "Der Schlüssel liegt ___ dem Handy gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_039_in", answer: "in", items: ["Das Handy liegt ___ dem Bett heute.", "Das Handy liegt ___ dem Bett jetzt.", "Der Hund schläft ___ dem Haus am Morgen.", "Sie ist ___ dem Kino bitte.", "Der Hund schläft ___ dem Haus gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_location_040_auf", answer: "auf", items: ["Das Bild hängt ___ der Wand heute.", "Wir sind ___ dem Balkon jetzt.", "Der Teller steht ___ dem Tisch am Morgen.", "Wir sind ___ dem Balkon bitte.", "Das Bild hängt ___ der Wand gleich."], meta:{ bucket:"location", case:"Dat" } },
      { id: "de_prep_dative_041_zu", answer: "zu", items: ["Wir fahren ___ der Schule.", "Geh bitte ___ der Küche.", "Sie geht ___ dem Bahnhof.", "Ich gehe ___ dem Arzt.", "Er kommt ___ der Arbeit."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_042_nach", answer: "nach", items: ["Ich fliege ___ Deutschland.", "Nach dem Essen gehen wir spazieren.", "Er geht ___ Hause.", "Wir fahren ___ Berlin.", "Sie kommt ___ dem Kurs nach Hause."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_043_von", answer: "von", items: ["Sie bekommt eine Nachricht ___ ihrem Bruder.", "Das Geschenk ist ___ meiner Schwester.", "Ich komme gerade ___ der Arbeit.", "Er nimmt das Buch ___ dem Tisch.", "Wir sprechen ___ dem Lehrer."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_044_bei", answer: "bei", items: ["Ich bin ___ dem Arzt.", "Das Treffen ist ___ der Schule.", "Er wohnt ___ seinen Eltern.", "Wir essen ___ meiner Mutter.", "Sie arbeitet ___ einer Firma."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_045_mit", answer: "mit", items: ["Ich gehe ___ meinem Freund.", "Er schreibt ___ einem Stift.", "Ich esse ___ einer Gabel.", "Wir spielen ___ dem Ball.", "Sie fährt ___ dem Bus."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_046_aus", answer: "aus", items: ["Sie trinkt ___ der Flasche.", "Wir gehen ___ dem Haus.", "Er nimmt das Buch ___ der Tasche.", "Der Ball fällt ___ dem Karton.", "Ich komme ___ der Schweiz."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_047_seit", answer: "seit", items: ["Es regnet ___ dem Morgen.", "Wir kennen uns ___ der Schule.", "Er arbeitet ___ Montag.", "Sie wohnt hier ___ zwei Monaten.", "Ich lerne Deutsch ___ einem Jahr."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_048_gegen\u00fcber", answer: "gegen\u00fcber", items: ["Ich gehe ___ das Haus heute.", "Ich gehe ___ das Haus jetzt.", "Leg das Buch ___ den Tisch am Morgen.", "Wir treffen uns ___ dem Park bitte.", "Ich bin ___ dem Haus gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_049_zu", answer: "zu", items: ["Ich gehe ___ dem Arzt heute.", "Geh bitte ___ der Küche jetzt.", "Er kommt ___ der Arbeit am Morgen.", "Ich gehe ___ dem Arzt bitte.", "Ich gehe ___ dem Arzt gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_050_nach", answer: "nach", items: ["Sie kommt ___ dem Kurs nach Hause heute.", "Er geht ___ Hause jetzt.", "Wir fahren ___ Berlin am Morgen.", "Er geht ___ Hause bitte.", "Wir fahren ___ Berlin gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_051_von", answer: "von", items: ["Ich komme gerade ___ der Arbeit heute.", "Er nimmt das Buch ___ dem Tisch jetzt.", "Das Geschenk ist ___ meiner Schwester am Morgen.", "Ich komme gerade ___ der Arbeit bitte.", "Ich komme gerade ___ der Arbeit gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_052_bei", answer: "bei", items: ["Wir essen ___ meiner Mutter heute.", "Das Treffen ist ___ der Schule jetzt.", "Er wohnt ___ seinen Eltern am Morgen.", "Das Treffen ist ___ der Schule bitte.", "Er wohnt ___ seinen Eltern gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_053_mit", answer: "mit", items: ["Ich gehe ___ meinem Freund heute.", "Er schreibt ___ einem Stift jetzt.", "Wir spielen ___ dem Ball am Morgen.", "Ich gehe ___ meinem Freund bitte.", "Ich gehe ___ meinem Freund gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_054_aus", answer: "aus", items: ["Sie trinkt ___ der Flasche heute.", "Sie trinkt ___ der Flasche jetzt.", "Ich komme ___ der Schweiz am Morgen.", "Sie trinkt ___ der Flasche bitte.", "Er nimmt das Buch ___ der Tasche gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_055_seit", answer: "seit", items: ["Wir kennen uns ___ der Schule heute.", "Er arbeitet ___ Montag jetzt.", "Er arbeitet ___ Montag am Morgen.", "Er arbeitet ___ Montag bitte.", "Er arbeitet ___ Montag gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_056_gegen\u00fcber", answer: "gegen\u00fcber", items: ["Ich gehe ___ das Haus heute.", "Ich bin ___ dem Haus jetzt.", "Das Buch liegt ___ dem Tisch am Morgen.", "Ich bin ___ dem Haus bitte.", "Wir treffen uns ___ dem Park gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_057_zu", answer: "zu", items: ["Sie geht ___ dem Bahnhof heute.", "Ich gehe ___ dem Arzt jetzt.", "Geh bitte ___ der Küche am Morgen.", "Geh bitte ___ der Küche bitte.", "Sie geht ___ dem Bahnhof gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_058_nach", answer: "nach", items: ["Ich fliege ___ Deutschland heute.", "Wir fahren ___ Berlin jetzt.", "Wir fahren ___ Berlin am Morgen.", "Sie kommt ___ dem Kurs nach Hause bitte.", "Wir fahren ___ Berlin gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_059_von", answer: "von", items: ["Ich komme gerade ___ der Arbeit heute.", "Ich komme gerade ___ der Arbeit jetzt.", "Wir sprechen ___ dem Lehrer am Morgen.", "Sie bekommt eine Nachricht ___ ihrem Bruder bitte.", "Das Geschenk ist ___ meiner Schwester gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_dative_060_bei", answer: "bei", items: ["Das Treffen ist ___ der Schule heute.", "Das Treffen ist ___ der Schule jetzt.", "Ich bin ___ dem Arzt am Morgen.", "Sie arbeitet ___ einer Firma bitte.", "Sie arbeitet ___ einer Firma gleich."], meta:{ bucket:"dative", case:"Dat" } },
      { id: "de_prep_accusative_061_f\u00fcr", answer: "f\u00fcr", items: ["Wir treffen uns ___ dem Park heute.", "Ich bin ___ dem Haus jetzt.", "Leg das Buch ___ den Tisch am Morgen.", "Ich bin ___ dem Haus bitte.", "Ich gehe ___ das Haus gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_062_ohne", answer: "ohne", items: ["Ich gehe ___ meinen Regenschirm.", "Wir fahren ___ Auto.", "Sie kommt ___ ihre Schwester.", "Er trinkt Kaffee ___ Milch.", "Ich kann nicht ___ dich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_063_durch", answer: "durch", items: ["Die Katze springt ___ die Tür.", "Er läuft ___ die Stadt.", "Ich schaue ___ das Fenster.", "Sie fährt ___ den Tunnel.", "Wir gehen ___ den Park."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_064_gegen", answer: "gegen", items: ["Wir sind ___ den Stress.", "Ich bin ___ diesen Plan.", "Er läuft ___ einen Baum.", "Sie spielt ___ den Computer.", "Der Ball fliegt ___ die Wand."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_065_um", answer: "um", items: ["Wir laufen ___ den See.", "Wir treffen uns ___ 8 Uhr.", "Er stellt den Stuhl ___ den Tisch.", "Sie sitzt ___ das Feuer.", "Der Weg geht ___ die Ecke."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_066_bis", answer: "bis", items: ["Warte ___ nächste Woche.", "Wir laufen ___ zum Bahnhof.", "Wir gehen ___ morgen.", "Ich arbeite ___ 18 Uhr.", "Der Kurs dauert ___ Freitag."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_067_f\u00fcr", answer: "f\u00fcr", items: ["Ich bin ___ dem Haus heute.", "Leg das Buch ___ den Tisch jetzt.", "Ich gehe ___ das Haus am Morgen.", "Wir treffen uns ___ dem Park bitte.", "Wir treffen uns ___ dem Park gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_068_ohne", answer: "ohne", items: ["Er trinkt Kaffee ___ Milch heute.", "Er trinkt Kaffee ___ Milch jetzt.", "Er trinkt Kaffee ___ Milch am Morgen.", "Ich kann nicht ___ dich bitte.", "Wir fahren ___ Auto gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_069_durch", answer: "durch", items: ["Ich schaue ___ das Fenster heute.", "Sie fährt ___ den Tunnel jetzt.", "Sie fährt ___ den Tunnel am Morgen.", "Ich schaue ___ das Fenster bitte.", "Wir gehen ___ den Park gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_070_gegen", answer: "gegen", items: ["Sie spielt ___ den Computer heute.", "Der Ball fliegt ___ die Wand jetzt.", "Der Ball fliegt ___ die Wand am Morgen.", "Sie spielt ___ den Computer bitte.", "Er läuft ___ einen Baum gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_071_um", answer: "um", items: ["Der Weg geht ___ die Ecke heute.", "Er stellt den Stuhl ___ den Tisch jetzt.", "Wir laufen ___ den See am Morgen.", "Wir laufen ___ den See bitte.", "Wir laufen ___ den See gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_072_bis", answer: "bis", items: ["Ich arbeite ___ 18 Uhr heute.", "Der Kurs dauert ___ Freitag jetzt.", "Warte ___ nächste Woche am Morgen.", "Warte ___ nächste Woche bitte.", "Wir laufen ___ zum Bahnhof gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_073_f\u00fcr", answer: "f\u00fcr", items: ["Ich bin ___ dem Haus heute.", "Ich gehe ___ das Haus jetzt.", "Das Buch liegt ___ dem Tisch am Morgen.", "Ich gehe ___ das Haus bitte.", "Leg das Buch ___ den Tisch gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_074_ohne", answer: "ohne", items: ["Wir fahren ___ Auto heute.", "Sie kommt ___ ihre Schwester jetzt.", "Er trinkt Kaffee ___ Milch am Morgen.", "Sie kommt ___ ihre Schwester bitte.", "Sie kommt ___ ihre Schwester gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_075_durch", answer: "durch", items: ["Ich schaue ___ das Fenster heute.", "Die Katze springt ___ die Tür jetzt.", "Er läuft ___ die Stadt am Morgen.", "Sie fährt ___ den Tunnel bitte.", "Die Katze springt ___ die Tür gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_076_gegen", answer: "gegen", items: ["Ich bin ___ diesen Plan heute.", "Ich bin ___ diesen Plan jetzt.", "Der Ball fliegt ___ die Wand am Morgen.", "Er läuft ___ einen Baum bitte.", "Sie spielt ___ den Computer gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_077_um", answer: "um", items: ["Sie sitzt ___ das Feuer heute.", "Wir treffen uns ___ 8 Uhr jetzt.", "Der Weg geht ___ die Ecke am Morgen.", "Der Weg geht ___ die Ecke bitte.", "Wir laufen ___ den See gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_078_bis", answer: "bis", items: ["Ich arbeite ___ 18 Uhr heute.", "Der Kurs dauert ___ Freitag jetzt.", "Der Kurs dauert ___ Freitag am Morgen.", "Wir laufen ___ zum Bahnhof bitte.", "Wir gehen ___ morgen gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_079_f\u00fcr", answer: "f\u00fcr", items: ["Ich bin ___ dem Haus heute.", "Ich bin ___ dem Haus jetzt.", "Leg das Buch ___ den Tisch am Morgen.", "Leg das Buch ___ den Tisch bitte.", "Das Buch liegt ___ dem Tisch gleich."], meta:{ bucket:"accusative", case:"Akk" } },
      { id: "de_prep_accusative_080_ohne", answer: "ohne", items: ["Sie kommt ___ ihre Schwester heute.", "Er trinkt Kaffee ___ Milch jetzt.", "Er trinkt Kaffee ___ Milch am Morgen.", "Ich kann nicht ___ dich bitte.", "Er trinkt Kaffee ___ Milch gleich."], meta:{ bucket:"accusative", case:"Akk" } },
    ]
  };
})();
